name: Cleanup Old Releases

on:
  workflow_run:
    workflows: ['Release']
    types:
      - completed

jobs:
  cleanup-releases:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Cleanup Old Releases
        uses: actions/github-script@v7
        with:
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            // Keep only the latest 3 releases
            const releasesToDelete = releases.data.slice(3);

            for (const release of releasesToDelete) {
              console.log(`Deleting release: ${release.name} (${release.tag_name})`);
              await github.rest.repos.deleteRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release.id
              });
              
              // Also delete the tag
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${release.tag_name}`
              });
            }

            console.log(`Kept ${Math.min(releases.data.length, 3)} latest releases`);
